<a href="https://colab.research.google.com/github/MilizCom/Data-mining/blob/main/Muhammad_Shamil_Izzah_A_Validasi_model602001222028.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Aimport pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_wine
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


In [ ]:
wine = load_wine()
X = wine.data
Y = wine.target
print(wine)


{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [ ]:
print("Data", wine.feature_names)
print("Target:", wine.target_names)


Data ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Target: ['class_0' 'class_1' 'class_2']


In [ ]:

# Assuming x and Y are already defined
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
model = GaussianNB()
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)

# Correct spelling of accuracy_score
accuracy = accuracy_score(Y_test, Y_pred)
print('Accuracy:', accuracy)


Accuracy: 0.9166666666666666


In [ ]:
sample = [[13.2, 1.71, 2.43, 15.6, 127, 2.8, 3.06, 0.28, 2.29, 5.64, 1.04, 3.92, 1065]]
prediction = model.predict(sample)
print('Prediction: ', prediction)

Prediction:  [0]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [ ]:
df = pd.read_excel('data.xlsx')  # Gantilah dengan path ke file CSV Anda


In [ ]:
print(df.head())       # Melihat beberapa baris pertama
print(df.info())       # Menampilkan tipe data dan jumlah data yang tersedia di tiap kolom
print(df.describe())   # Menampilkan statistik deskriptif dataset


   PatientID    State     Sex GeneralHealth   AgeCategory  HeightInMeters  \
0          1  Alabama  Female          Fair  Age 75 to 79            1.63   
1          2  Alabama  Female     Very good  Age 65 to 69            1.60   
2          3  Alabama    Male     Excellent  Age 60 to 64            1.78   
3          4  Alabama    Male     Very good  Age 70 to 74            1.78   
4          5  Alabama  Female          Good  Age 50 to 54            1.68   

   WeightInKilograms        BMI  HadHeartAttack  HadAngina  ...  \
0          84.820000  32.099998               0          1  ...   
1          71.669998  27.990000               0          0  ...   
2          71.209999  22.530001               0          0  ...   
3          95.250000  30.129999               0          0  ...   
4          78.019997  27.760000               0          0  ...   

                             ECigaretteUsage  ChestScan  \
0  Never used e-cigarettes in my entire life          1   
1  Never used e-

In [ ]:
print(df.columns)


Index(['PatientID', 'State', 'Sex', 'GeneralHealth', 'AgeCategory',
       'HeightInMeters', 'WeightInKilograms', 'BMI', 'HadHeartAttack',
       'HadAngina', 'HadStroke', 'HadAsthma', 'HadSkinCancer', 'HadCOPD',
       'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis',
       'HadDiabetes', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty',
       'DifficultyConcentrating', 'DifficultyWalking',
       'DifficultyDressingBathing', 'DifficultyErrands', 'SmokerStatus',
       'ECigaretteUsage', 'ChestScan', 'RaceEthnicityCategory',
       'AlcoholDrinkers', 'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver',
       'TetanusLast10Tdap', 'HighRiskLastYear', 'CovidPos'],
      dtype='object')


In [ ]:
# Mengonversi kolom 'SmokerStatus' menjadi numerik
df['SmokerStatus'] = df['SmokerStatus'].map({'Never us': 0, 'Former us': 1, 'Current us': 2})


In [ ]:
# Menghapus kolom 'HadDiabetes' dari fitur dan menjadikannya kolom target
X = df.drop('HadDiabetes', axis=1)  # Menghapus kolom 'HadDiabetes' dari fitur
y = df['HadDiabetes']  # Kolom target


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

# Assuming 'df' is your DataFrame

# ... (your previous code to load and preprocess data) ...

# Get a list of all object (string) columns
object_cols = df.select_dtypes(include=['object']).columns.tolist()

# Perform one-hot encoding for all object columns
# We remove 'HadDiabetes' assuming it is your target variable
categorical_features = [col for col in object_cols if col != 'HadDiabetes']
df = pd.get_dummies(df, columns=categorical_features, drop_first=True)
# drop_first=True to avoid multicollinearity

# Menghapus kolom 'HadDiabetes' dari fitur dan menjadikannya kolom target
X = df.drop('HadDiabetes', axis=1)  # Menghapus kolom 'HadDiabetes' dari fitur
y = df['HadDiabetes']  # Kolom target


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = model.predict(X_test)

# Menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi:", accuracy)

# Menampilkan laporan klasifikasi
print("Laporan Klasifikasi:\n", classification_report(y_test, y_pred))

# Menampilkan matriks konfusi
print("Matriks Konfusi:\n", confusion_matrix(y_test, y_pred))


Akurasi: 0.8096410385894037


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Laporan Klasifikasi:
                                          precision    recall  f1-score   support

                                     No       0.84      0.96      0.89     39419
No, pre-diabetes or borderline diabetes       0.00      0.00      0.00       980
                                    Yes       0.29      0.11      0.16      6725
Yes, but only during pregnancy (female)       0.00      0.00      0.00       402

                               accuracy                           0.81     47526
                              macro avg       0.28      0.27      0.26     47526
                           weighted avg       0.74      0.81      0.76     47526

Matriks Konfusi:
 [[37734     0  1685     0]
 [  878     0   102     0]
 [ 5980     0   745     0]
 [  375     0    27     0]]


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

# ... (your previous code to load and preprocess data) ...

# Get a list of all object (string) columns
object_cols = df.select_dtypes(include=['object']).columns.tolist()

# Perform one-hot encoding for all object columns
# We remove 'HadDiabetes' assuming it is your target variable
categorical_features = [col for col in object_cols if col != 'HadDiabetes']
df = pd.get_dummies(df, columns=categorical_features, drop_first=True)
# drop_first=True to avoid multicollinearity

# Menghapus kolom 'HadDiabetes' dari fitur dan menjadikannya kolom target
X = df.drop('HadDiabetes', axis=1)  # Menghapus kolom 'HadDiabetes' dari fitur
y = df['HadDiabetes']  # Kolom target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

model = GaussianNB()
model.fit(X_train, y_train)

# Assuming your original sample data before one-hot encoding
original_sample = [65, 1, 0, 0, 0, 160, 70, 27.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# Create a DataFrame with the original features
original_sample_df = pd.DataFrame([original_sample], columns=df.drop('HadDiabetes', axis=1).columns[:len(original_sample)])

# Now apply the same one-hot encoding used during training
sample_df = pd.get_dummies(original_sample_df, columns=categorical_features, drop_first=True)

# Ensure sample_df has the same columns as X_train
# Add missing columns with 0 values if any
missing_cols = set(X_train.columns) - set(sample_df.columns)
for col in missing_cols:
    sample_df[col] = 0

# Reorder columns to match X_train
sample_df = sample_df[X_train.columns]


# Now you can predict using the processed sample
prediction = model.predict(sample_df)
print("Prediksi untuk sampel baru:", prediction)

Prediksi untuk sampel baru: ['Yes']


In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_wine
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
# Import necessary libraries for classification metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
!pip install openpyxl
import openpyxl
df = pd.read_excel('Patients Data ( Used for Heart Disease Prediction ) (1).xlsx', engine='openpyxl') # Use openpyxl engine explicitly



In [7]:
# Preprocessing (same as before)
df['SmokerStatus'] = df['SmokerStatus'].map({'Never us': 0, 'Former us': 1, 'Current us': 2})
object_cols = df.select_dtypes(include=['object']).columns.tolist()
categorical_features = [col for col in object_cols if col != 'HadDiabetes']
df = pd.get_dummies(df, columns=categorical_features, drop_first=True)
X = df.drop('HadDiabetes', axis=1)
y = df['HadDiabetes']


In [8]:
# Comparison 1: 100 data points, 2 features
def comparison_1():
    # Randomly select 100 data points and 2 features
    np.random.seed(42)  # for reproducibility
    indices = np.random.choice(len(X), 100, replace=False)
    X_sample = X.iloc[indices, :2]  # Selecting the first 2 columns as features
    y_sample = y.iloc[indices]

    X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size=0.2, random_state=0)
    model = GaussianNB()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print("Comparison 1 (100 data, 2 features): Accuracy =", accuracy)

In [9]:
comparison_1()

Comparison 1 (100 data, 2 features): Accuracy = 0.85


In [10]:
def comparison_2():
    # Randomly select 150 data points and 3 features
    np.random.seed(42)  # for reproducibility
    indices = np.random.choice(len(X), 150, replace=False)
    X_sample = X.iloc[indices, :3] # Selecting the first 3 columns as features
    y_sample = y.iloc[indices]

    X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size=0.2, random_state=0)
    model = GaussianNB()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print("Comparison 2 (150 data, 3 features): Accuracy =", accuracy)


In [11]:
comparison_2()

Comparison 2 (150 data, 3 features): Accuracy = 0.7333333333333333
